# Generated by Django 4.0.4 on 2022-05-26 07:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_todo_created_at_local_todo_created_at_server_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='created_at_local',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 26, 7, 38, 21, 953019, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='todo',
            name='created_at_server',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 26, 7, 38, 21, 952832, tzinfo=utc)),
        ),
    ]
