# Generated by Django 4.0.4 on 2022-05-27 05:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_todo_created_at_local_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='todo',
            name='created_at_local',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 27, 10, 25, 49, 465213)),
        ),
        migrations.AlterField(
            model_name='todo',
            name='created_at_server',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 27, 10, 25, 49, 465102)),
        ),
    ]
