# Generated by Django 4.0.4 on 2022-05-30 04:04

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('is_favorite', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_complete', models.BooleanField(default=False)),
                ('created_at_server_time', models.DateTimeField(default=datetime.datetime(2022, 5, 30, 9, 4, 20, 166263))),
                ('target_date', models.DateTimeField(default=datetime.datetime(2022, 5, 30, 9, 4, 20, 166509))),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
