# Generated by Django 4.0.4 on 2022-06-01 12:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_todo_created_at_server_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='created_at_server_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 1, 17, 27, 34, 181830)),
        ),
        migrations.AlterField(
            model_name='todo',
            name='target_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 1, 17, 27, 34, 181830)),
        ),
    ]
