# Generated by Django 4.0.5 on 2022-06-05 08:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_todo_created_at_server_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='is_complete',
            new_name='is_completed',
        ),
        migrations.AlterField(
            model_name='todo',
            name='created_at_server_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 5, 13, 33, 34, 332551)),
        ),
        migrations.AlterField(
            model_name='todo',
            name='target_date',
            field=models.DateField(default=datetime.datetime(2022, 6, 5, 13, 33, 34, 332551)),
        ),
    ]
