# Generated by Django 4.0.4 on 2022-05-26 07:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_todo'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='created_at_local',
            field=models.DateField(default=datetime.datetime(2022, 5, 26, 7, 34, 27, 292240, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='todo',
            name='created_at_server',
            field=models.DateField(default=datetime.datetime(2022, 5, 26, 7, 34, 27, 292125, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='todo',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='todo',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
