# Generated by Django 4.0.4 on 2022-05-26 08:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_todo_created_at_local_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='created_at_local',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 26, 13, 26, 10, 867643)),
        ),
        migrations.AlterField(
            model_name='todo',
            name='created_at_server',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 26, 13, 26, 10, 867531)),
        ),
    ]
