# Generated by Django 4.0.4 on 2022-05-30 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_todo_is_complete_alter_todo_created_at_local_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Todo',
        ),
    ]
