# Generated by Django 4.0.6 on 2022-08-04 14:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_todo_created_date_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='created_date_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 4, 14, 5, 51, 769858, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='todo',
            name='target_date_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 4, 14, 5, 51, 769858, tzinfo=utc)),
        ),
    ]
