# Generated by Django 4.0.6 on 2022-08-04 13:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='created_date_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 4, 13, 49, 23, 445190, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='todo',
            name='target_date_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 4, 13, 49, 23, 445190, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='todo',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
